version: '3'
services:
    redis:
      container_name: redis
      hostname: redis
      image: redis:6.0.8
      restart: always
      environment:
        TZ: Asia/Shanghai
      command: ["redis-server","/etc/redis/redis.conf"]
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /opt/redis/redis.conf:/etc/redis/redis.conf
        - /opt/redis/data:/data
      ports:
        - 6379:6379
